Network capture
Botnet-Honeypot/Honeypot pull request #67
Opened 2021-04-07 22:12 UTC by Sannholm

- Starts and stops tcpdump container along side target container
- Attaches to target container network to capture traffic for each session in isolation
- Stores captured network traffic in volume
- Additional option (`ENABLE_ISOLATED_TARGET_CONTAINER_NETWORKS`) to put each target container on its own network to make sure no broadcast traffic is redundantly captured. Also makes it so one target container cannot "see" other target containers.

How to test:
- Start like usual with `docker-compose up --build`
- Login to honeypot: `ssh localhost`
- Run a command which causes network traffic, e.g. `curl http://info.cern.ch/` (intentionally not HTTPS)
- Open `\\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes\openssh-serverXXXX_netlog\log.pcap` in Wireshark and inspect network traffic

Known limitations:
- Encrypted network traffic cannot be decrypted since no encryption keys are currently collected.

Known issues:
- Option `ENABLE_ISOLATED_TARGET_CONTAINER_NETWORKS` is currently disabled by default since it does seems to start erroring after a while with many connections. The reason might be that Docker is running out of subnets, but I am not sure.

2021-04-09 10:21 UTC, osksvan requested changes
AcquireTargetSystem now waits until all YieldTargetSystem are finished, resulting in long wait time for the new session. 
Completing YieldTargetSystem requests seem to take more time now compared to before, which further adds to the previous point.
![image](https://user-images.githubusercontent.com/10566507/114166476-108aa880-992e-11eb-8079-d5f5fd83375c.png)

2021-04-09 20:14 UTC, Sannholm commented
> AcquireTargetSystem now waits until all YieldTargetSystem are finished, resulting in long wait time for the new session.
> Completing YieldTargetSystem requests seem to take more time now compared to before, which further adds to the previous point.
> ![image](https://user-images.githubusercontent.com/10566507/114166476-108aa880-992e-11eb-8079-d5f5fd83375c.png)

@osksvan I've now changed it so it should not unnecessarily block. Please have a look again!

2021-04-10 07:19 UTC, osksvan approved these changes

2021-04-10 14:22 UTC, ALX99 commented
Works well for me!

2021-04-10 14:22 UTC, ALX99 approved these changes

2021-04-10 16:14 UTC, merged