Frontend regex deny & % successrate
Botnet-Honeypot/Honeypot pull request #71
Opened 2021-04-09 09:55 UTC by ALX99

- Adds the ability to match regex on usernames and password and deny the login attempt
- Adds the ability to provide a percentage chance of a successful login

2021-04-09 11:43 UTC, Sannholm requested changes
Looks good! However, instead of using the regex to deny usernames and passwords could we instead have it replace `SSH_ALLOWED_USERNAMES` and `SSH_ALLOWED_PASSWORDS`? I'm thinking that a regex `^(bob|alice)$` would be the same as setting `SSH_ALLOWED_USERNAMES=bob:alice`. At the moment that functionality is duplicated.

Additionally, what if you want to apply the `SSH_LOGIN_SUCCESS_RATE` but only to the people who are allowed by the regex. Could we maybe have it do the chance check after checking if they were allowed by username and password?

2021-04-09 17:34 UTC, Sannholm submitted a review, later dismissed
Nice! Good work!

2021-04-09 17:47 UTC, osksvan submitted a review, later dismissed
Seems to be working well, good job.
`re.compile(r"linus")
 re.compile(r"torvalds")` :smile:

2021-04-09 20:18 UTC, Sannholm approved these changes

2021-04-10 07:13 UTC, osksvan approved these changes

2021-04-10 12:01 UTC, merged