Python environment setup
Botnet-Honeypot/Honeypot pull request #8
Opened 2021-02-17 00:13 UTC by Sannholm

2021-02-17 08:21 UTC, ALX99 requested changes
.gitignore should probably not ignore `.vscode/`. You could place settings there which every user has to use to make the code more consistent. I have the following for example
```json
  "autoDocstring.docstringFormat": "google",
  "python.linting.enabled": true,
  "python.formatting.provider": "autopep8",
  "python.analysis.typeCheckingMode": "basic",
  "python.analysis.autoImportCompletions": true,
  "python.linting.pylintEnabled": true,
```

pylintrc is should probably be named .pylintrc as it seems more common and will be a hidden file under linux. (Config files are rarely touched and is better hidden)

2021-02-19 11:48 UTC, ALX99 submitted a review, later dismissed
The environment works for me (testing inside WSL)

2021-02-22 12:17 UTC, ALX99 approved these changes

2021-02-22 12:20 UTC, tvigg approved these changes

2021-02-22 12:49 UTC, merged